sudo: required
services:
  - docker

before_install:
  - docker build -t ranew/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ranew/react-test npm test -- --coverage

after_success:
  - docker build -t ranew/multi-client ./client
  - docker build -t ranew/multi-nginx ./nginx
  - docker build -t ranew/multi-server ./server
  - docker build -t ranew/multi-worker ./worker
  # log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push ranew/multi-client
  - docker push ranew/multi-nginx
  - docker push ranew/multi-server
  - docker push ranew/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-469946907492
  bucket_path: docker-multi
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY